### ISSUE TITLE
OpenSource HMIPServer

### ISSUE THREAD

**Issue by chdxD1** [eq-3/occu#107]
Im HMIPServer werden Klassen vom Eclipse Smarthome (https://github.com/eclipse/smarthome) verwemdet. Diese stehen unter der EPL-2.0 Lizenz. Dies würde bedeuten, dass nach 3.1a dieser Lizenz der **Quellcode der Java Anwendung veröffentlicht oder herausgegeben** werden muss.

Ich würde also darum bitten, diese Applikation unter einer mit der EPL-2.0 kompatiblen Lizenz zur Verfügung zu stellen.

**Comment by eq-3-occu** [comment]
Hallo Christopher (chdxD1),

wir haben Ihre Bitte zur Kenntnis genommen und kümmern uns darum.
Gerne möchten wir auch anbieten mit Ihnen persönlich in Kontakt zu treten.
Bitte melden Sie sich hierzu unter support@eq-3.de mit dem zusätzlichen Hinweis "z.Hd. Teamleitung Support", der betreffende Personenkreis ist diesbezüglich bereits informiert worden.

Freundliche Grüße,
Ihr eq3-occu Team

**Comment by psi-4ward** [comment]
Closed ohne weitere Informationen?
