### ISSUE TITLE
rfd warning /etc/config/firmware

### ISSUE THREAD

**Issue by hobbyquaker** [eq-3/occu#11]
rfd schreibt ins log:
`<Warning> opendir(/etc/config/firmware//) failed`

scheint keinen Impact zu haben, aber dennoch unschön ;)

**Comment by wowi1968** [comment]
Kann über User Firmware Dir=/home/user/myUploadedFirmware in der rfd.conf gesetzt werden. In dem Verzeichnis befinden sich die Geräte Firmware Dateien für Live OTAU. Über die CCU2 WebUI können dort z.B. Dateien abgelegt werden.
