### ISSUE TITLE
rfd logging in Datei

### ISSUE THREAD

**Issue by hobbyquaker** [eq-3/occu#12]
Kann man das Log auch in eine Datei umleiten wenn rfd/hs485d als daemon läuft? via Log Destination = /pfad/logfile in der Config hat es nicht geklappt.

**Comment by wowi1968** [comment]
Beim rfd sollte das mit Log Destination=File und Log Filename=xyz gehen. Ob das beim hs485d geht muss ich prüfen lassen.

**Comment by hobbyquaker** [comment]
Beim rfd funktioniert es, Danke für die Info. hs485d teste ich asap :)

**Comment by hobbyquaker** [comment]
Eben hs485d getestet - der ignoriert das leider und loggt weiterhin ins syslog.
