### ISSUE TITLE
JSON-RPC API: Whats the prefered way to aquire a _session_id_ from my CCu3?

### ISSUE THREAD

**Issue by firsttris** [eq-3/occu#120]
I tried to use the Session.Login Method but the CCu3 only returns "method not found"
https://github.com/eq-3/occu/blob/master/WebUI/www/api/methods/session/login.tcl#L2

![image](https://user-images.githubusercontent.com/1709260/200156627-f4aaec67-21f4-48d3-bf15-d560af6c33dd.png)
![image](https://user-images.githubusercontent.com/1709260/200156639-ee18de38-185f-499d-930e-fd8993bc2fca.png)

Other functions (like Room.getAll) are working fine if I add a valid _session_id_

what am i doing wrong?

whats the recommanded way to aquire a _session_id_?

**Comment by firsttris** [comment]
after studying the source code i found that its just this comment which is wrong
https://github.com/eq-3/occu/blob/master/WebUI/www/api/methods/session/login.tcl#L2

the methodname is Session.login instead of Session.Login

**Comment by jp112sdl** [comment]
In the `methods.conf` it is documented correctly
https://github.com/eq-3/occu/blob/26f63a4820907230a589a1654387001c62a7aa51/WebUI/www/api/methods.conf#L759-L764

**Comment by jens-maus** [comment]
Comments are comments and should IMHO not be taken as serious are the filename and the main docu.
