### ISSUE TITLE
USB Stick

### ISSUE THREAD

**Issue by hobbyquaker** [eq-3/occu#22]
Hallo Wolfgang,
Rainer hat eben mal versucht rfd mit dem USB Stick zu testen (siehe http://homematic-forum.de/forum/viewtopic.php?f=56&t=25512) - hat leider nicht hingehauen. Ich weiss allerdings auch nicht ob die von Hmcon erzeugte Config so passt:

```
Log Level = 1
Persist Keys = 1
# PID File = /opt/hmcon/var/rfd/rfd.pid
# UDS File = /opt/hmcon/var/rfd/socket_rfd
Device Description Dir = /opt/hmcon/firmware/rftypes
Device Files Dir = /opt/hmcon/var/rfd/devices
Key File = /opt/hmcon/var/rfd/keys
Address File = /opt/hmcon/var/rfd/ids
Firmware Dir = /opt/hmcon/firmware
User Firmware Dir = /opt/hmcon/var/firmware
XmlRpcHandlersFile = /opt/hmcon/var/rfd/RFD.handlers
Replacemap File = /opt/hmcon/firmware/rftypes/replaceMap/rfReplaceMap.xml
[Interface 0]
Type = USB Interface
Serial Number = JEQ0701199
```

System scheint den Stick zu erkennen, hier dmesg:

```
[  720.826347] usb 1-1: new full-speed USB device number 2 using ci_hdrc
[  720.949828] usb 1-1: New USB device found, idVendor=1b1f, idProduct=c00f
[  720.949843] usb 1-1: New USB device strings: Mfr=4, Product=14, SerialNumber=                                                              36
[  720.949853] usb 1-1: Product: HM-CFG-USB
[  720.949862] usb 1-1: Manufacturer: eQ-3
[  720.949870] usb 1-1: SerialNumber: JEQ0701199
[  720.959328] hid-generic 0003:1B1F:C00F.0001: hiddev0,hidraw0: USB HID v1.10 Device [eQ-3 HM-CFG-USB] on usb-ci_hdrc.0-1/input0
[ 1715.922537] usb 1-1: USB disconnect, device number 2
[ 2071.122074] usb 1-1: new full-speed USB device number 3 using ci_hdrc
[ 2071.244833] usb 1-1: New USB device found, idVendor=1b1f, idProduct=c00f
[ 2071.244848] usb 1-1: New USB device strings: Mfr=4, Product=14, SerialNumber=  36
[ 2071.244860] usb 1-1: Product: HM-CFG-USB
[ 2071.244869] usb 1-1: Manufacturer: eQ-3
[ 2071.244877] usb 1-1: SerialNumber: JEQ0701199
[ 2071.252510] hid-generic 0003:1B1F:C00F.0002: hiddev0,hidraw0: USB HID v1.10 Device [eQ-3 HM-CFG-USB] on usb-ci_hdrc.0-1/input0
```

RFD schreibt folgendes ins Log:

```
2015/06/09 18:50:34.618 <Info> BidCoS-Service started
2015/06/09 18:50:34.619 <Info> XmlRpc Server is listening on TCP port 2001
2015/06/09 18:50:34.624 <Error> All USB-Interfaces are in use by other applications
2015/06/09 18:50:34.624 <Error> No BidCoS-Interface available
2015/06/09 18:50:34.624 <Warning> Error initializing interfaces
```

Ist die rfd-Config so ausreichend?

Viele Grüße,
Sebastian

**Comment by phonovision** [comment]
Das Gerät scheint zumindest erkannt zu werden, sonst würde statt

```
<Error> All USB-Interfaces are in use by other applications
```

etwas wie 

```
<Error> No USB interface found
```

als Fehler ausgegeben werden.

Bei mir funktioniert es, ich habe aber noch `Description = ...` im `[Interface 0]`-Block angegeben. Vielleicht ist das nicht optional?

Ansonsten könnte es sein, dass das Gerät bei dir schon durch einen anderen Prozess in Beschlag genommen wurde.

**Comment by wowi1968** [comment]
Im HomeMatic Forum (http://homematic-forum.de/forum/viewtopic.php?f=56&t=24791#p214643) wurde das auch schon mal diskutiert. Dort war es der udev, der sich das Device vor dem RFD geschnappt hat. Mit folgender udev-rule kann man das verhindern:

SUBSYSTEM=="usb", ATTR{idVendor}=="1b1f", ATTR{idProduct}=="c00f", OPTIONS+="ignore_device", OPTIONS+="last_rule"

**Comment by hobbyquaker** [comment]
Hab das Problem gefunden:
Hmcon startet den rfd mit einem nicht-priviligierten User, der hatte schlicht keine Rechte das HID-Device zu öffnen. Konnte das mit folgender udev-rule umgehen:
`SUBSYSTEM=="usb", ATTR{idVendor}=="1b1f", ATTR{idProduct}=="c00f", USER="hmcon"`
allerdings funktionierte das in meinen Tests nur unter Debian Wheezy (armhf), unter Ubuntu 14.04 (amd64) hat es nicht geklappt: 

```
2015/06/10 18:10:22.199 <Debug> Detaching device 1B1F/C00F from kernel driver
2015/06/10 18:10:22.201 <Error> Unexpected end of descriptor at 33, tag=0x09, type=0, bytes=1
2015/06/10 18:10:22.201 <Error> Reading HID report descriptor failed
2015/06/10 18:10:22.201 <Error> USB-Interface LEQ1516962 is in use by an other application
2015/06/10 18:10:22.201 <Error> No BidCoS-Interface available
2015/06/10 18:10:22.201 <Warning> Error initializing interfaces
```

Die "Holzhammermethode" funktionierte dann allerdings auch unter Ubuntu:
`SUBSYSTEM=="usb", ATTR{idVendor}=="1b1f", ATTR{idProduct}=="c00f", MODE="0666"` - warum versuche ich bei Gelegenheit mal zu erforschen. 

Ist also eigentlich gar kein RFD-Thema sondern betrifft einfach hid devices, udev und libusb.

**Comment by wowi1968** [comment]
Kann damit der Issue geschlossen werden?

**Comment by Homoran** [comment]
Ja,
Installation läuft
