### ISSUE TITLE
Systemsteuerung:Zentralenwatrung

### ISSUE THREAD

**Issue by jakespeed1311** [eq-3/occu#26]
Hallo,
nach installation.. wollte ich meine Alte Config einlesen aber ! Jeder Browser hängt wenn ich auf Systemsteuerung gehe und es erscheint irgendwann die Meldung REGA Eine Komponente Reagiert nicht. 
Wann gibt es eine Vernünfige anleitung für Normalos ?  Init.d usw..  Ich versuche mit Debian zu arbeiten so wird das alles sehr schwer.. Oder ist das hier schon wieder TOT ?
Jake

**Comment by wowi1968** [comment]
Hallo Jake,

das OCCU SDK ist ein Software Development Kit und kann als Basis für eigene Distributionen benutzt werden, stellt aber selbst keine fertige Distribution zur Verfügung. Leider haben seit der Veröffentlichung nur wenige sich damit beschäftigt (siehe "Community Projects" in der Readme). Es gibt auch eine Firma, die auf dem Usertreffen im April eine Zentrale angekündigt hat, die auf OCCU basieren wird. eQ-3 selbst wird in den nächsten Tagen ein Rasberry Pi 2 Image zur Verfügung stellen, das zusammen mit dem HM-MOD-RPI-PCB Modul im nächsten ELV-Journal benutzt werden kann. Das Image ist analog zum CCU2 Image aufgebaut. Anli aus dem Forum wollte an Debian Images arbeiten, weiß aber nicht, wie weit er damit ist.

Dein Fehler dürfte damit zusammenhängen, dass die WebUI vermutlich Dateien wie z.B. VERSION nicht findet. Wenn du kein Entwickler bist, solltest du besser auf eine fertige Distribution oder Debian Packages warten.

**Comment by jakespeed1311** [comment]
Hi, Danke für die Antwort. Nun ich bin zwar kein Linux guru aber es sollte schon so sein das ein Packet welches installiert auch eine gewisse anleitung mitbringt.  Schön wenn ELV das Modul rausbringt aber ich hätte eine gewisse anleitung für das SDK erwartet Ich hätte mir gewünscht es unter native Linux X86 laufen lassen zu können. Nun ja ein PI soll es werden auch gut. 
Erstmal vielen dank!
Gruß Jake
