### ISSUE TITLE
Please update firmware/rftypes for new devices

### ISSUE THREAD

**Issue by stargo** [eq-3/occu#36]
It seems that the device-definitions in [firmware/rftypes](https://github.com/eq-3/occu/tree/master/firmware/rftypes) are not updated with new devices introduced in recent firmware-versions (like HM-OU-CFM-TW).
Please update these definitions so newer devices can be used.

**Comment by eq-3-occu** [comment]
add missing firmware files and create new 2.19.9-1 release.
