### ISSUE TITLE
rfd daemon doesn't start on Raspbian

### ISSUE THREAD

**Issue by zioalex** [eq-3/occu#41]
Hi,
I am trying to run the full stack on a Raspbian installation.
I got the follow error when I try to start the rfd daemon:
```
root@raspberrypi:/etc/config# /bin/rfd  -f /etc/config/rfd.conf -l 0 -c
2017/04/06 07:20:25.843 <Info> BidCoS-Service started
2017/04/06 07:20:25.852 <Info> XmlRpc Server is listening on TCP port 2001
2017/04/06 07:20:25.861 <Debug> CCU2CommController::init() - Improved initialization.
2017/04/06 07:20:25.862  CCU2CommController::SendSystemCommdand()
2017/04/06 07:20:25.862  CCU2CommController::SendSystemCommdand() sending: fd 00 03 00 00 00 18 00
2017/04/06 07:20:25.863 <Debug> CCU2CommController::improvedInit() - Coprocessor state could not be determined.
2017/04/06 07:20:25.863 <Error> CCU2CommController::improvedInit() - Identify response string not handled:
2017/04/06 07:20:30.865 <Debug> CCU2CommController::improvedInit() - Timeout while waiting for coprocessor application
2017/04/06 07:20:30.865  CCU2CommController::SendSystemCommdand()
2017/04/06 07:20:30.866  CCU2CommController::SendSystemCommdand() sending: fd 00 04 00 01 0a 00 3d 2c
2017/04/06 07:20:30.866 <Error> () CCU2CommController::setCSMACAEnabled(): Error disabling CSMA/CA.
2017/04/06 07:20:30.866 <Error> No BidCoS-Interface available
2017/04/06 07:20:30.866 <Warning> Error initializing interfaces
```
Please can you help with this problem?
Kind Regards
Alessandro

**Comment by bepat** [comment]
Hi,
are you using a Raspberry Pi 3?
On the Pi 3 the serial port is mapped to the bluetooth modem by default.
You have to change this by adding the following line to the file /boot/config.txt
dtoverlay=pi3-miniuart-bt

regards,
Benedikt

**Comment by zioalex** [comment]
Hi Benedikt,
yes I do.
Okey Dokey I will try later.
Thanks for the suggestion!

Cheers
Alessandro

**Comment by zioalex** [comment]
I tried,
but I get the same error:
root@raspberrypi:/etc/init.d# /bin/rfd  -f /etc/config/rfd.conf -l 0 -c
2017/04/10 23:47:38.615 <Info> BidCoS-Service started
2017/04/10 23:47:38.616 <Info> XmlRpc Server is listening on TCP port 2001
2017/04/10 23:47:38.619 <Debug> CCU2CommController::init() - Improved
initialization.
2017/04/10 23:47:38.619  CCU2CommController::SendSystemCommdand()
2017/04/10 23:47:38.619  CCU2CommController::SendSystemCommdand() sending:
fd 00 03 00 00 00 18 00
2017/04/10 23:47:38.619 <Debug> CCU2CommController::improvedInit() -
Coprocessor state could not be determined.
2017/04/10 23:47:38.619 <Error> CCU2CommController::improvedInit() -
Identify response string not handled:
2017/04/10 23:47:43.621 <Debug> CCU2CommController::improvedInit() -
Timeout while waiting for coprocessor application
2017/04/10 23:47:43.621  CCU2CommController::SendSystemCommdand()
2017/04/10 23:47:43.621  CCU2CommController::SendSystemCommdand() sending:
fd 00 04 00 01 0a 00 3d 2c
2017/04/10 23:47:43.621 <Error> () CCU2CommController::setCSMACAEnabled():
Error disabling CSMA/CA.
2017/04/10 23:47:43.622 <Error> No BidCoS-Interface available
2017/04/10 23:47:43.622 <Warning> Error initializing interfaces

Do I need a special kernel module to use it?
Kind regards
Alessandro

**Comment by zioalex** [comment]
I also tried with the same config.txt  as the homematic-raspi distro:
```
# Please note that this is only a sample, we recommend you to change it to fit
# your needs.
# You should override this file using a post-build script.
# See http://buildroot.org/manual.html#rootfs-custom
# and http://elinux.org/RPiconfig for a description of config.txt syntax

kernel=zImage

# To use an external initramfs file
#initramfs rootfs.cpio.gz

# Disable overscan assuming the display supports displaying the full resolution
# If the text shown on the screen disappears off the edge, comment this out
disable_overscan=1

# How much memory in MB to assign to the GPU on Pi models having
# 256, 512 or 1024 MB total memory
gpu_mem_256=100
gpu_mem_512=100
gpu_mem_1024=100

dtparam=i2c_arm=on
dtparam=i2s=on
dtparam=spi=on

# enable the UART
enable_uart=1

# make sure the uart is running at 48MHz
init_uart_clock=48000000

# disable the bluetooth UART use and
# disable the uart1 alltogether
dtoverlay=pi3-disable-bt
dtparam=uart1=off

# disable the splash screen
disable_splash=1

# activating the hardware watchdog
dtparam=watchdog=on

```

But I have the same result.

**Comment by zioalex** [comment]
I found out that the device file /dev/bcm2835-raw-uart is not present although the kernel modules ( bcm2835_raw_uart , eq3_char_loop ), that I suppose should create it, are loaded correctly:
```
root@raspberrypi:/etc/init.d# modinfo  eq3_char_loop
filename:       /lib/modules/4.4.50-v7+/extra/eq3_char_loop.ko
license:        GPL
description:    eQ-3 IPC loopback char driver
srcversion:     4A89A12F5F97580769D2D3B
depends:        
vermagic:       4.4.50-v7+ SMP mod_unload modversions ARMv7 
root@raspberrypi:/etc/init.d# modinfo bcm2835_raw_uart
filename:       /lib/modules/4.4.50-v7+/extra/broadcom/bcm2835_raw_uart.ko
author:         eQ-3 Entwicklung GmbH
license:        GPL
description:    eQ-3 raw BCM2835 uart driver
srcversion:     556DBE73AAFC2A565F72C2F
depends:        
vermagic:       4.4.50-v7+ SMP mod_unload modversions ARMv7 
```

I ran out of ideas...:-O

**Comment by bepat** [comment]
Hi Alessandro,
I remember, that it was a bit tricky to get this working on the Pi 3.
My /boot/config.txt also contains another line, I have added:
```
enable_uart=1
dtoverlay=pi3-miniuart-bt
```
This is my /boot/cmdline.txt:
`dwc_otg.lpm_enable=0 console=tty1 root=/dev/mmcblk0p2 rootfstype=ext4 elevator=deadline fsck.repair=yes rootwait`
I don't know, if it is the default version or if I changed it.

You can also enable the serial port using raspi-config.

regards,
Benedikt

**Comment by zioalex** [comment]
Hi Benedikt!
No way :-( the cmd boot options are the same and I enabled the serial port ans the I2C interface but nothing changed. Moreover I cannot understand if they were already enabled.

Best Regards
Alessandro

**Comment by YoungCereal** [comment]
Hi,
One small question. Do you have a Homematic-Chip attached to the raspberry?
Without one, this will never work. 

From your post above:
2017/04/10 23:47:43.622 <Error> No BidCoS-Interface available

Best Regards
Michael

**Comment by zioalex** [comment]
Hi Michael,
yep that is a bit obvious but yes. :-) 

Initially, I thought that it was not well connected but then when I switch the SD card and put in the homematic-raspi everything works properly. It needs to something in the config / kernel / or whatever...

I think that message occurs because the kernel drivers is not working properly.

Best Regards
Alessandro

**Comment by YoungCereal** [comment]
OK thats good :), you have switched to the dualcore firmware ?
Can you post your config files of rfd.conf, crRFD.conf, multimacd.conf.
Plus an dmsg output from the homematic part :).
It looks as if the multimacd does not came up.

Best Regards
Michael

**Comment by drose28357** [comment]
Why don't you use this ready-to-use image ? It is based on this OCCU repository und is compiled für RPi2/3.

https://github.com/jens-maus/RaspberryMatic

**Comment by zioalex** [comment]
@YoungCereal Umh. Not aware of what the dualcore firmware is it! How can I check it?
The infos I can see are:
'''
Linux raspberrypi 4.4.50-v7+ #970 SMP Mon Feb 20 19:18:29 GMT 2017 armv7l GNU/Linux
Raspbian GNU/Linux 8
'''
I attached all the relevant infos I could find. Nothing useful in the dmesg.

[crRFD.conf.txt](https://github.com/eq-3/occu/files/919039/crRFD.conf.txt)
[multimacd.conf.txt](https://github.com/eq-3/occu/files/919043/multimacd.conf.txt)
[rfd.conf.txt](https://github.com/eq-3/occu/files/919040/rfd.conf.txt)
[S00eQ3SystemStart.log.txt](https://github.com/eq-3/occu/files/919041/S00eQ3SystemStart.log.txt)
[S61rfd.log.txt](https://github.com/eq-3/occu/files/919042/S61rfd.log.txt)

**Comment by zioalex** [comment]
@drose28357 I started with that one and I do not have any problem with it. But I need a general Linux distro so I can install whatever I need. Otherwise the Rasperry is limited to be mainly an homematic device.

**Comment by jens-maus** [comment]
@zioalex Then please have a look at YAHM (https://github.com/leonsio/YAHM) which should be exactly what you want. And please note that this is no help fora here but an issue tracking system. So if you want to install all binaries on your own, you are on your own. So either use YAHM or RaspberryMatic if you want a working solution.

**Comment by zioalex** [comment]
Hi @jens-maus, thanks for your suggestion  I will have a look to the YAHM project. 
Unfortunately I find quite limiting to have a Raspberry device mostly dedicated to this and therefore the RaspeberryMatic project doesn't fits my need.

I know that this is not an help forum. But I have a problem, most probably, with the kernel driver provided in this project. The aim of this project is to provide the tools to use the homematic devices or not?

If I find a problem it should be handled...

**Comment by leonsio** [comment]
With YAHM you have Original CCU Firmware running inside LXC Container (like docker) on raspberry pi. 
You can also install any other tools you need on native Debian Jessie inside raspberry. 
With the last develop-branch commit you will find support for homematic ip protocol 

Leo

**Comment by zioalex** [comment]
Hi @leonsio  I am trying YAHM and it is really promising :-) we can get in touch over there. Unfortunately the docs is only in German that make the process a bit more difficult for me.

**Comment by leonsio** [comment]
For English documentation see the source code ;)
You can use google translator to translate complete site

**Comment by zioalex** [comment]
After a lot of troubleshooting with @leonsio now I have a running homematic installation in an LXC container. For reference you can have a look here https://github.com/leonsio/YAHM/issues/109.
