### ISSUE TITLE
hmipserver ping/pong support

### ISSUE THREAD

**Issue by hobbyquaker** [eq-3/occu#42]
hmserver does not generate a PONG event when sending a PING.

**Comment by jens-maus** [comment]
Also here, please provide example code how you send the PING so that everyone can reproduce it with a simple command execution in a shell.

**Comment by hobbyquaker** [comment]
It's just the RPC command 'ping' as described in http://www.eq-3.de/Downloads/eq3/download%20bereich/hm_web_ui_doku/HM_XmlRpc_API.pdf Chapter 4.3.37

`$ echo "load tclrpc.so; puts [xmlrpc 'http://127.0.0.1:2010' ping test]" | tclsh`

**Comment by eq-3-occu** [comment]
fixed with 71ed37e
