### ISSUE TITLE
x86 ReGaHss Beta

### ISSUE THREAD

**Issue by quickmic** [eq-3/occu#46]
x86 Version hat ein Problem mit einer Library...

/bin/ReGaHss: error while loading shared libraries: libXmlRpc.so: wrong ELF class: ELFCLASS32

"wrong ELF class" sagt aus, dass "ReGaHss" und "libXmlRpc.so" gegen unterschiedliche Architekturen kompiliert wurden.
Da die "libXmlRpc.so" nicht upgedatet wurde vermute ich, dass "ReGaHss" als amd64 kompiliert wurde, aber "libXmlRpc.so" als x86 (ELFCLASS32 wird vermutlich 32 bit bedeuten).
btw, es waere sowieso schoen, wenn alles gegen x86 und amd64 kompiliert wird in Zukunft

**Comment by eq-3-occu** [comment]
Beta Version von ReGaHss sollte nun auch wie bisher auch ELF 32-bit sein. Ob eine amd64 Variante zur Verfügung gestellt werden kann, muss noch intern bei eQ-3 ermittelt werden.
