### ISSUE TITLE
hmip_networkkey.conf bzw. Network.Key

### ISSUE THREAD

**Issue by leonsio** [eq-3/occu#47]
Gibt es irgendwie eine Dokumentation hinsichtlich des Network.Key bzw. der hmip_networkkey.conf? 

ist es frei definierbarer String? 
ist das ein MD5 hash (weil aktuell 32 Zeichen)?
Sind alle Zeichen erlaubt, oder nur Hex (0-9A-F)?

die Datei scheint in der aktuellen CCU2 Firmware zu fehlen, wird diese automatisch angelegt? von welchem Prozess und kann man dies irgendwie beeinflussen? Ist die Datei überhaupt relevant?

**Comment by eq-3-occu** [comment]
Bei Homematic IP ist es so, dass im normalen Betrieb der Netzwerkschlüssel vom Coprozessor zufällig bestimmt wird. Dieser Netzwerkschlüssel verlässt niemals unverschlüsselt den Corpo. Um einen Zentralentausch zu ermöglichen, wird der Netzwerkschlüssel verschlüsselt unter /etc/config/crRFD/data/[SGTIN].apkx abgelegt. 

Der Netzwerkkey besteht aus einem zufälligen 16 Byte Hexstring, z.B. 167E4B49F5E2EF207BD1F14FB2A48E59

In der CCU2 Beta Firmware, in der die HmIP Integration getestet wurde, wurde ein Netzwerkschlüssel über die Datei hmip_networkkey.conf vorgegeben, um die Möglichkeit zu haben, bei Problemen den Funkverkehr mittels eines Sniffers entschlüsseln zu können. Für den normalen Betrieb ist die Datei daher nicht relevant.

**Comment by leonsio** [comment]
Sorry wenn ich erneut nachhacke, aber was bedeutet "einen Zentralentausch zu ermöglichen, wird der Netzwerkschlüssel verschlüsselt unter xyz abgelegt."
mich würde quasi dieser Fall interessieren, bei dem die Zentralle getauscht wird, bzw. ein Wechsel von der CCU zu HM-MOD-URAT erfolgt


wird fpr den Fall diese Datei verwendet?


Danke  leo



 Von:   eq-3-occu <notifications@github.com> 
 An:   eq-3/occu <occu@noreply.github.com> 
 Kopie:   Leonid Kogan <leon@leonsio.com>, Author <author@noreply.github.com> 
 Gesendet:   26.04.2017 10:47 
 Betreff:   Re: [eq-3/occu] hmip_networkkey.conf bzw. Network.Key (#47) 


Bei Homematic IP ist es so, dass im normalen Betrieb der Netzwerkschlüssel vom Coprozessor zufällig bestimmt wird. Dieser Netzwerkschlüssel verlässt niemals unverschlüsselt den Corpo. Um einen Zentralentausch zu ermöglichen, wird der Netzwerkschlüssel verschlüsselt unter xyz abgelegt. 
Der Netzwerkkey besteht aus einem zufälligen 16 Byte Hexstring, z.B. 167E4B49F5E2EF207BD1F14FB2A48E59 
In der CCU2 Beta Firmware, in der die HmIP Integration getestet wurde, wurde ein Netzwerkschlüssel über die Datei hmip_networkkey.conf vorgegeben, um die Möglichkeit zu haben, bei Problemen den Funkverkehr mittels eines Sniffers entschlüsseln zu können. Für den normalen Betrieb ist die Datei daher nicht relevant.

**Comment by eq-3-occu** [comment]
Habe xxx im Post noch mal angepasst (/etc/config/crRFD/data/[SGTIN].apkx). Nur die Datei /etc/config/crRFD/data/[SGTIN].apkx für den Zentralentausch benötigt, die Datei hmip_networkkey.conf nur wenn man sniffen will.
