### ISSUE TITLE
Deaktivierung der verschlüsselung

### ISSUE THREAD

**Issue by Doccos** [eq-3/occu#52]
Da ich meinen Lan Adapter auch mit Fhem verwende, wollte ich fragen ob es einen Befehl für die "rfd.conf" gibt, um die Verschlüsselung zu Deaktivieren.

Derzeit wird mir folgender Fehler angezeigt:
`2017/08/12 16:29:31.885 <Info> BidCoS-Service started
2017/08/12 16:29:31.885 <Info> XmlRpc Server is listening on TCP port 2001
2017/08/12 16:29:31.886 <Debug> Default interface is now LEQxxxxxx
2017/08/12 16:29:31.894 <Error> Lan Interface LEQxxxxxx is not configured for encryption while we are
2017/08/12 16:29:31.894 <Warning> LEQxxxxxx: Invalid hello message received: 
2017/08/12 16:29:31.894 <Info> Disconnected from Lan Interface LEQxxxxxx
2017/08/12 16:29:31.894 <Debug> Event: LEQxxxxxx.CONNECTED=false
2017/08/12 16:29:31.894 <Error> No BidCoS-Address set and no Interface to beg it from
`

**Comment by eq-3-occu** [comment]
Ja, man kann die Verschlüsselung abschalten. Allerdings nicht über die rfd.conf sondern mit Hilfe der Netfinder Software (http://www.eq-3.de/Downloads/Software/NetFinder.zip). In der Liste das Gateway auswählen und über den Button "Netzwerkeinstellungen ändern" die Verschlüsselung aus schalten.
