### ISSUE TITLE
HMServer Fehler in Heizungsgruppen ohne Thermostat

### ISSUE THREAD

**Issue by thkl** [eq-3/occu#56]
Wenn eine Heizungsgruppe nur aus Ventilen (HM - nicht IP) besteht und kein Thermostat hat, dann wird seit Firmware 2.27.8 die Ist Temperatur nicht mehr richtig ermittelt. Die Temperatur der Gruppe steht dann auf 20° C.  

Mit einem Thermostat tritt der Fehler nicht auf.

**Comment by jens-maus** [comment]
Das Problem ist schon bekannt und sollte mit der nächsten kommenden Firmware repariert sein.

**Comment by thkl** [comment]
👍  Ok prima .. ich wollte es nur irgendwo mal aufschreiben. Nicht das es dann heisst, hättest Du mal was gesagt ... :)

**Comment by eq-3-occu** [comment]
mit 2.29.22 behoben
