### ISSUE TITLE
mangelhaft implementierte Funktion zum Löschen von "Geistervariablen"

### ISSUE THREAD

**Issue by BadenPower** [eq-3/occu#60]
#Die Funktion zum automatischen Löschen der einem Benutzer zugeordneten "falschen" ID, zur Anzeige auf der Startseite, wurde mangelhaft implementiert.

Durch die falsche Verwendung von .UserSharedObjects() werden beim Start der ReGaHss Beta24 nicht alle IDs der "Geistervariablen" und "Schläfer" gelöscht.

**Comment by jens-maus** [comment]
Duplikat von https://github.com/jens-maus/RaspberryMatic/issues/196
