### ISSUE TITLE
libusb fehlt

### ISSUE THREAD

**Issue by hobbyquaker** [eq-3/occu#7]
seit #4 benötigt rfd die libusb, ist aber nicht mitgeliefert

**Comment by wowi1968** [comment]
Hab ich eigentlich bewusst nicht mit ausgeliefert, da möglichst immer die nativ Libraries der Distributionen verwendet werden sollten. Hilft den Pflegeaufwand (z.B. für Security Fixes) zu reduzieren. Sollte bei zukünftigen Debian Packages als Abhängigkeit eingetragen sein. Von daher würde ich den Issue gerne schließen. OK?

**Comment by hobbyquaker** [comment]
Ok, verstehe. Dann nehm ich das mal mit ins hmcon-script auf.
