### ISSUE TITLE
Absichtlich fehlerhafte Methoden in ReGaHss reaktiviert

### ISSUE THREAD

**Issue by BadenPower** [eq-3/occu#71]
Der Entwickler der ReGaHss hat absichtlich Skript-Methoden in der ReGaHss reaktiviert, welche für die Verwendung auf bestimmte Objekte nicht zulässig waren und sind und normalerweise in einem Skriptfehler enden müßten.

Dies geschah nur zu dem Zweck, seine fehlerhaft programmierten Skripte, wie zum Beispiel dieses
https://homematic-forum.de/forum/viewtopic.php?f=27&t=31353 nicht richtig programmieren zu müssen, oder um die fehlerhafte Programmierung zu verschleiern, da das Skript bei richtig arbeitender ReGaHss zu einem Abbruch des Skriptes führt. 

Dies betrifft zum Beispiel die Methode .Device() auf einen Datenpunkt, und die Methode .LastTimestamp() auf einen Kanal. Beide Methoden werden in dem verlinkten Skript fehlerhaft verwendet und führten so korrekterweise mit der Version 0109 der ReGaHss zu einem Abbruch.

Das reaktivierten der Methoden geschah in Version 0111 bzw. 0112 und liefern seither falsche Ergebnisse zurück, nur damit sie im verlinkten Skript so verwendet werden können.

Ansinnen der Arbeiten an der ReGaHss sollte jedoch sein, die Fehler der ReGaHss zu beseitigen und nicht fehlerhaft arbeitenden Methoden aus Eigennutz zu reaktievieren.
 
Anmerkung:
Die Wahrheit sollte auch in einem Issue- und Bugtracker nicht gelöscht werden.

**Comment by Apollon77** [comment]
Die Unterstellung der Absicht mal weggelassen ist die echte Frage für ein Issue damit, ob "zum Beispiel die Methode .Device() auf einen Datenpunkt, und die Methode .LastTimestamp() auf einen Kanal" erlaubt sein sollen oder nicht. 

DAS sollte im Issue diskutiert werden. Vllt überlegst Du ja eine Umformulierung

**Comment by BadenPower** [comment]
Schau Dir doch einfach einmal an, was die Methode .Device() auf einen Hss-Datenpunkt zurückgibt.
Auf alle Fälle kein Gerät. Also ist das Ergebnis falsch. Und nur wer mit einem falschen Ergebnis weiterarbeiten muss, der benötigt diese Funktion.

Ausserdem stellt sich die Frage, weshalb die Methode .Device() auch für andere Objekte, welche überhaupt keinem Gerät zugeordnet werden können, wieder reaktiviert wurden, wie zum Beispiel dem Objekttyp OT_CALENDARDP, obwohl die Methode auf diesen und andere Objekttypen noch nie zulässig war.

Bei .LastTimeStamp() auf einen Kanal ist es so, dass es dort schon immer die Abfragemöglichkeit über .LastDpActionTime() gibt, was die korrekte Abfrage war und ist. Weshalb wurde also eine Methode reaktiviert, welche das gleiche Ergebnis liefert, aber vom kontextbezogenen Rückgabewert nicht das liefert, was die gleiche Methode auf andere Objekte, auf welche sie zulässig war/ist, zurückliefert?

**Comment by litti** [comment]
Aus Deiner Sicht hört es sich so an, als gäbe es nur einen Entwickler der ReGaHss ("Der Entwickler der ReGaHss"). Du meinst hier jmaus, dessen Skript Du ja auch verlinkst. Leider sind Deine Schlussfolgerungen ("Die Wahrheit"), dass dieser Entwickler die Funktionen aus Eigennutz wieder reaktiviert hat, nicht richtig.
Gerne kläre ich auf, wie die Sache wirklich liegt: jmaus hat Rega-Script um die Funktionen bereinigt. Es wurde von den Verantwortlichen jedoch festgestellt, dass viele Skripte die bereinigten Funktionen nutzen. Aus diesem Grund wurde vom Entwicklergremium entschieden, die Funktionen wieder zu aktivieren um die Kompatibilität zu erhalten.

Noch ein Hinweis zum Umgang mit diesem Tool: Dieser Bugtracker ist für sachliche Diskussionen zu verwenden. Eine sachliche Diskussion zu diesem Punkt sähe aus meiner Sicht so ähnlich aus wie der Post von Apollon77, evtl. angereichert um Beispiele. Zur Klärung persönlicher Differenzen oder Darstellung von vermuteten Wahrheiten ist dieser Bugtracker nicht zu verwenden.
