### ISSUE TITLE
RFD.handlers

### ISSUE THREAD

**Issue by hobbyquaker** [eq-3/occu#8]
Die RFD.handlers wird nach /var geschrieben, kann dieser Pfad via rfd.conf gesetzt werden? Falls nicht würde ich das gerne auf die Wunschliste setzen ;)

**Comment by wowi1968** [comment]
Geht momentan noch nicht, hab einen Change Request dazu erfasst.

**Comment by wowi1968** [comment]
kann seit pull request #20 mit XmlRpcHandlersFile=/hm/opt/var/RFD.handlers gesetzt werden.
