### ISSUE TITLE
Release 2.35.16

### ISSUE THREAD

**Issue by alexreinert** [eq-3/occu#80]
Please update the repository to 2.35.16 and add a tag for the version.
Thanks.

**Comment by jens-maus** [comment]
As a temporary workaround you can use my fork (https://github.com/jens-maus/occu) of the occu repository. There you will see a 2.35.15 and 2.35.16 tag as well as all latest changes being integrated until this repository is being updated...

**Comment by alexreinert** [comment]
Thanks Jens, I know that repository.
But as this is the official repository, which is also linked on the RPI-RF-MOD product page in the ELV web shop, it should be updated as well, because not everyone knows your fork.

**Comment by jens-maus** [comment]
I fully agree, but that's exactly why I posted the link in this ticket now, so that people will notice it.

**Comment by jens-maus** [comment]
done!

**Comment by alexreinert** [comment]
Thanks!
