### ISSUE TITLE
HmIP-MOD-OC8 Tasterkanäle werden nicht per XML-RPC Events gesendet

### ISSUE THREAD

**Issue by dersimn** [eq-3/occu#86]
Das Ausgangsmodul HmIP-MOD-OC8 hat 8 Tasterkanäle und 8 Ausgänge, die im Werkszustand mit einer internen Direktverknüpfung belegt sind.

Laut `getParamsetDescription` Funktion in XML-RPC, erzeugen diese Tasten auch die von Homematic (classic) bekannten Events `PRESS_SHORT` bzw. `PRESS_LONG`. Diese Events werden jedoch nicht per XML-RPC gesendet. Das HmIP-MOD-OC8 lässt sich mittels XML-RPC daher nur als reiner Aktor betreiben.

Dabei spielt es keine Rolle ob die Direktverknüpfung aktiv ist oder gelöscht wurde.

**Comment by hobbyquaker** [comment]
vielleicht fehlt da nur ein `reportValueUsage`, siehe https://github.com/jens-maus/RaspberryMatic/issues/399

**Comment by dersimn** [comment]
#DingeDieInDerAnleitungEinfachNichtEindeutigGenugBeschriebenWerden
