### ISSUE TITLE
master branch

### ISSUE THREAD

**Issue by quickmic** [eq-3/occu#87]
Please update the master branch to 3.41.11
Currently master has 3.41.7 with some updates to 3.42.X so it's a mixture...

thx

**Comment by jens-maus** [comment]
The master branch is a development branch. If you want to have the latest 3.41.x version use the b_3_41 branch.

**Comment by quickmic** [comment]
I don't get it. Master should always have the latest versions correct? In fact it hasn't.
Version b_3_41 is newer than master.
b_3_41 has 3.41.11
master has mainly 3.41.7 code (older versions than b_3_41) with some mods from 3.42.X
At the moment master got older code than b_3_41 but with updates to 3.42.X

**Comment by jens-maus** [comment]
Please give an example where master has older code than b_3_41

**Comment by quickmic** [comment]
https://imgur.com/a/DTvxNom

First picture is from b_3_41, second from master.

**Comment by quickmic** [comment]
Konnte das Problem nachvollzogen werden? Im Moment ist es bloed, dass ich die aktuellen codes manuell zusammenkopieren muss.

**Comment by jens-maus** [comment]
Mach dir halt nen Fork und merge alles selbst zusammen. Ich maintaine ja auch einen occu fork für RaspberryMatic.

**Comment by quickmic** [comment]
Sorry, das war nicht direkt an dich gerichtet und soll auch keine Beschwerde sein. Ich hoffe aber doch, dass jemand direkt von eq3 mitliest. Ich weiss nicht wie hier (im GIT) die Policies sind. Situation ist jedenfalls nicht schoen in Moment.
Und nein, ich forke nicht. Dazu hab ich echt keine Zeit. CCU ist nicht mein einziges Bastelptojekt an dem ich simultan arbeite.

**Comment by jens-maus** [comment]
eQ3 weiss davon, aber genau wie du haben die eben andere Prioritäten. Es bleibt dir also nichts anderes üblich als abzuwarten und Tee zu trinken bis hier agiert wird.

**Comment by quickmic** [comment]
@all Thank you for the update!
