### ISSUE TITLE
HmIPserver.jar works, but throws constant error message "Could not register BidCos-RF_java"

### ISSUE THREAD

**Issue by agrimpelhuber** [eq-3/occu#90]
Running HmIPserver.jar *only* on port 2010 of a Home Assistant / Raspberry Pi 3. The package there extracts and runs core components from the OCCU release. Basically, the module sets up and runs the Server against the HmIP USB stick with the following command line:

`java -Xmx64m -Dlog4j.configuration=file:///etc/config/log4j.xml -Dfile.encoding=ISO-8859-1 -jar /opt/HMServer/HMIPServer.jar /etc/config/crRFD.conf &`

The server works great! However, it complains about not being able to set up the BidCos cache on startup, and then constantly throws this error:

`2019-01-22 07:01:05,725 [ERROR] BidCosRpcDispatcher - Could not register BidCos-RF_java`

I would like to work on my configuration to fix this minor issue. However, I have no idea where the message comes from, and couldn't find any information. To my understanding, this looks as if it comes from the "old" BidCos protocol - which I'm not running. The fact that this message does not seem to affect functionality seems a strong point in case.

Anyone able to fix this, or point me to a solution?

**Comment by ToSa27** [comment]
Do you have a `InterfacesList.xml` file in your config directory? If so, check if there is a section like this
```
	<ipc>
	 	<name>BidCos-RF</name>
	 	<url>xmlrpc_bin://127.0.0.1:2001</url> 
	 	<info>BidCos-RF</info> 
	</ipc>
```
and remove it so that it not even tries to get the BidCos-RF interface initialized. If the file does not exist, I don't know what defaults HMIPServer uses but probably you would need to create one.

I'm interested in a similar setup as well. Are you planning to build a Hass Add-On around this?

**Comment by jens-maus** [comment]
Also have a look how other projects are dealing with HMIPServer.jar startup. For example in RaspberryMatic you can find the corresponding HMIPServer startup section here:

https://github.com/jens-maus/RaspberryMatic/blob/master/buildroot-external/overlay/base/etc/init.d/S62HMServer#L77

Note, that compared to your example it also receives a `/etc/HMServer.conf` config file which contains the following here:

```
hmServerPort=39292
regaPort=31999
```

**Comment by agrimpelhuber** [comment]
Thanks! Both of you!

I tried both things (at once - I know, bad way to find the actual reason). Result: The error messages seem to have gone. I strongly suspect the "InterfacesList.xml" fix to have done the work, but I can only say for sure once I have tried both things isolated. BTW, I needed to modify the "hmServerPort" to "9292", which is where my "VirtualDevices" interface is running. It has been running there all the time, stopped working when I added the "/etc/HMServer.conf" with port 39292, and worked again when I changed that to 9292. That's why I think that the InterfacesList was the thing that did it.

I can only test this once I can restart the (productive) OCCU, and then I'll post the results here.

But maybe to explain all this, and to answer the question of @ToSa27 

> I'm interested in a similar setup as well. Are you planning to build a Hass Add-On around this?

There is actually an add-on already at https://github.com/home-assistant/hassio-addons/tree/master/homematic. As you can see, it's actually a **hass.io** add-on - don't know whether that will run on other home assistant installations. Probably not, because hass.io add-ons are docker-based, making it quite easy to use an existing project like OCCU and make it run on the Raspi running Home Assistant.

As far as I can tell, the add-on pulls the OCCU sources, modifies them in some places, adds some configuration from the hass.io interface, and a start script, and runs OCCU in a docker container. Since the standard add-on wasn't working for me, I am currently working on a local copy to fix some issues, and finally suggest them to the add-on Github project.

Funny enough, I just noticed that somebody has commited a change that removes InterfacesList.xml altogether. (https://github.com/home-assistant/hassio-addons/commit/f550d6dce7fd5d3079b7ca00068c03beb64343c6). Maybe it's redudant, just causing the error messages I noticed. The add-on itself seems to configure the interfaces somewhere else. I'll try that version as soon as possible.

**Comment by ToSa27** [comment]
@agrimpelhuber when I looked at the existing homematic add-on some time ago, it had some significant issues with HmIP (might be fixed now) and my setup is 99% HmIP. I'm thinking about getting rid of the two remaining pure Homematic devices. With a pure HmIP setup and a backend like Home Assistant (or OpenHAB or ioBroker or...) the occu comes with a ton of functionality that is actually redundant. A slim hass.io add-on with just a fully working HMIPServer.jar is likely all I need, just didn't have the time to dig into the details.

**Comment by agrimpelhuber** [comment]
@ToSa27 as far as I can see, this is exactly what the Add-On does. The docker container basically just extracts the necessary files from the OCCU package to run a bare-bone HmIP server (and nothing else, if BidCos or wired devices are turned off). That's the case for me right now - just the XML-RPC backend. Then, the HM _component_ of Home Assistant provides a nice interface for the backbone, but that has nothing to do with OCCU. No (O)CCU web interface, in particular. A friend who has a CCU2 warned me ;-)

The problems I'm encountering are just cosmetic (like error messages) come from the fact that I can't find any information on how the HmIPServer.jar is properly run. For example, why does it do BidCos stuff even though the add-on only runs the HmIP component? Does it try to talk to the BidCos server? If yes, how do I turn it off?

What I'm saying: I have exactly the same goal as you, and I'm 90% there, by tweaking the hass.io package.
